const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.wrap,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Blocos: 0},
	{Variável1: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{DestruirForaDoLayout: 0},
	{Projétil: 0},
	{Mago: 0},
	{Vida: 0},
	{Goblin: 0},
	{Esmaecer: 0},
	{Magia: 0},
	{PontoDeLuz: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{GameOver: 0},
	{DarAVolta: 0},
	{Fantasma: 0},
	{Ghost: 0},
	{Teclado: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Senóide: 0},
	{Botão: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{ESC: 0},
	{PONTUAÇÃO: 0},
	{pontos_ghost: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Blocos: class extends self.ITiledBackgroundInstance {},
	Mago: class extends self.ISpriteInstance {},
	Goblin: class extends self.ISpriteInstance {},
	Magia: class extends self.ISpriteInstance {},
	PontoDeLuz: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	Fantasma: class extends self.ISpriteInstance {},
	Ghost: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Botão: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	ESC: class extends self.ITextInstance {}
}